server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /hooks/ {
        proxy_pass http://ops-webhook:9000;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
